#include <stdint.h>

typedef enum
{
	CD3DX_REGISTER_INDEX_ARG = 0,
	CD3DX_REGISTER_COUNT_ARG = 1,
	CD3DX_PARAMETER_CLASS_ARG = 2,
	CD3DX_PARAMETER_TYPE_ARG = 3,
	CD3DX_ELEMENTS_ARG = 4,
	CD3DX_NUM_ARGS = 5
} _3607;

