#include <stdint.h>

typedef enum
{
	kCGLPFAAllRenderers = 1,
	kCGLPFADoubleBuffer = 5,
	kCGLPFAStereo = 6,
	kCGLPFAAuxBuffers = 7,
	kCGLPFAColorSize = 8,
	kCGLPFAAlphaSize = 11,
	kCGLPFADepthSize = 12,
	kCGLPFAStencilSize = 13,
	kCGLPFAAccumSize = 14,
	kCGLPFAMinimumPolicy = 51,
	kCGLPFAMaximumPolicy = 52,
	kCGLPFAOffScreen = 53,
	kCGLPFAFullScreen = 54,
	kCGLPFASampleBuffers = 55,
	kCGLPFASamples = 56,
	kCGLPFAAuxDepthStencil = 57,
	kCGLPFAColorFloat = 58,
	kCGLPFAMultisample = 59,
	kCGLPFASupersample = 60,
	kCGLPFASampleAlpha = 61,
	kCGLPFARendererID = 70,
	kCGLPFASingleRenderer = 71,
	kCGLPFANoRecovery = 72,
	kCGLPFAAccelerated = 73,
	kCGLPFAClosestPolicy = 74,
	kCGLPFARobust = 75,
	kCGLPFABackingStore = 76,
	kCGLPFAMPSafe = 78,
	kCGLPFAWindow = 80,
	kCGLPFAMultiScreen = 81,
	kCGLPFACompliant = 83,
	kCGLPFADisplayMask = 84,
	kCGLPFAPBuffer = 90,
	kCGLPFARemotePBuffer = 91,
	kCGLPFAVirtualScreenCount = 128
} _CGLPixelFormatAttribute;

