#include <stdint.h>

typedef enum
{
	CUBEMAPSHOT_NONE = 0,
	CUBEMAPSHOT_UP = 1,
	CUBEMAPSHOT_DOWN = 2,
	CUBEMAPSHOT_LEFT = 3,
	CUBEMAPSHOT_RIGHT = 4,
	CUBEMAPSHOT_FRONT = 5,
	CUBEMAPSHOT_BACK = 6,
	CUBEMAPSHOT_COUNT = 7
} CubemapShot;

