#include <stdint.h>

typedef enum
{
	FXCHAN_COLOR = 0,
	FXCHAN_COLOR_RAND = 1,
	FXCHAN_ALPHA = 2,
	FXCHAN_ALPHA_RAND = 3,
	FXCHAN_SIZE = 4,
	FXCHAN_SIZE_RAND = 5,
	FXCHAN_SIZE2 = 6,
	FXCHAN_SIZE2_RAND = 7,
	FXCHAN_LENGTH = 8,
	FXCHAN_LENGTH_RAND = 9,
	FXCHAN_ROTATION_DELTA = 10,
	FXCHAN_ROTATION_DELTA_RAND = 11,
	FXCHAN_VELOCITY_X = 12,
	FXCHAN_VELOCITY_Y = 13,
	FXCHAN_VELOCITY_Z = 14,
	FXCHAN_VELOCITY_X_RAND = 15,
	FXCHAN_VELOCITY_Y_RAND = 16,
	FXCHAN_VELOCITY_Z_RAND = 17,
	FXCHAN_VELOCITY2_X = 18,
	FXCHAN_VELOCITY2_Y = 19,
	FXCHAN_VELOCITY2_Z = 20,
	FXCHAN_VELOCITY2_X_RAND = 21,
	FXCHAN_VELOCITY2_Y_RAND = 22,
	FXCHAN_VELOCITY2_Z_RAND = 23,
	FXCHAN_COUNT = 24
} FxChannelId;

