#include <stdint.h>

typedef enum
{
	R_DRAWGROUP_DEPTH_PREPASS = 0,
	R_DRAWGROUP_SHADOW_COOKIE = 1,
	R_DRAWGROUP_WORLD_SUN = 2,
	R_DRAWGROUP_WORLD_REMAINDER = 3,
	R_DRAWGROUP_POST_AA = 4,
	R_DRAWGROUP_COUNT = 5
} GfxDrawGroupType;

