#include <stdint.h>

typedef enum
{
	HE_TYPE_FREE = 0,
	HE_TYPE_TEXT = 1,
	HE_TYPE_VALUE = 2,
	HE_TYPE_PLAYERNAME = 3,
	HE_TYPE_MAPNAME = 4,
	HE_TYPE_GAMETYPE = 5,
	HE_TYPE_MATERIAL = 6,
	HE_TYPE_TIMER_DOWN = 7,
	HE_TYPE_TIMER_UP = 8,
	HE_TYPE_TENTHS_TIMER_DOWN = 9,
	HE_TYPE_TENTHS_TIMER_UP = 10,
	HE_TYPE_CLOCK_DOWN = 11,
	HE_TYPE_CLOCK_UP = 12,
	HE_TYPE_WAYPOINT = 13,
	HE_TYPE_COUNT = 14
} he_type_t;

