#include <stdint.h>

typedef enum
{
	HITLOC_NONE = 0,
	HITLOC_HELMET = 1,
	HITLOC_HEAD = 2,
	HITLOC_NECK = 3,
	HITLOC_TORSO_UPR = 4,
	HITLOC_TORSO_LWR = 5,
	HITLOC_R_ARM_UPR = 6,
	HITLOC_L_ARM_UPR = 7,
	HITLOC_R_ARM_LWR = 8,
	HITLOC_L_ARM_LWR = 9,
	HITLOC_R_HAND = 10,
	HITLOC_L_HAND = 11,
	HITLOC_R_LEG_UPR = 12,
	HITLOC_L_LEG_UPR = 13,
	HITLOC_R_LEG_LWR = 14,
	HITLOC_L_LEG_LWR = 15,
	HITLOC_R_FOOT = 16,
	HITLOC_L_FOOT = 17,
	HITLOC_GUN = 18,
	HITLOC_NUM = 19
} hitLocation_t;

