#include <stdint.h>

typedef enum
{
	LANGUAGE_ENGLISH = 0,
	LANGUAGE_FRENCH = 1,
	LANGUAGE_GERMAN = 2,
	LANGUAGE_ITALIAN = 3,
	LANGUAGE_SPANISH = 4,
	LANGUAGE_BRITISH = 5,
	LANGUAGE_RUSSIAN = 6,
	LANGUAGE_POLISH = 7,
	LANGUAGE_KOREAN = 8,
	LANGUAGE_TAIWANESE = 9,
	LANGUAGE_JAPANESE = 10,
	LANGUAGE_CHINESE = 11,
	LANGUAGE_THAI = 12,
	LANGUAGE_LEET = 13,
	MAX_LANGUAGES = 14
} language_t;

