#include <stdint.h>

typedef enum
{
	TEXTURE_SRC_CODE_BLACK = 0,
	TEXTURE_SRC_CODE_WHITE = 1,
	TEXTURE_SRC_CODE_IDENTITY_NORMAL_MAP = 2,
	TEXTURE_SRC_CODE_SPECULARITY = 3,
	TEXTURE_SRC_CODE_SMODEL_LIGHTING = 4,
	TEXTURE_SRC_CODE_LIGHT_GRID_WEIGHTS_0 = 5,
	TEXTURE_SRC_CODE_LIGHT_GRID_WEIGHTS_1 = 6,
	TEXTURE_SRC_CODE_LIGHTMAP_WEIGHTS = 7,
	TEXTURE_SRC_CODE_LIGHTMAP_0 = 8,
	TEXTURE_SRC_CODE_LIGHTMAP_1 = 9,
	TEXTURE_SRC_CODE_LIGHTMAP_2 = 10,
	TEXTURE_SRC_CODE_LIGHTMAP_3 = 11,
	TEXTURE_SRC_CODE_SHADOWCOOKIE = 12,
	TEXTURE_SRC_CODE_FEEDBACK = 13,
	TEXTURE_SRC_CODE_RESOLVED_POST_SUN = 14,
	TEXTURE_SRC_CODE_RESOLVED_SCENE = 15,
	TEXTURE_SRC_CODE_SKY = 16,
	TEXTURE_SRC_CODE_LIGHT0_ATTENUATION = 17,
	TEXTURE_SRC_CODE_LIGHT1_ATTENUATION = 18,
	TEXTURE_SRC_CODE_DYNAMIC_SHADOWS = 19,
	TEXTURE_SRC_CODE_OUTDOOR = 20,
	TEXTURE_SRC_CODE_FLOATZ = 21,
	TEXTURE_SRC_CODE_SUN_HALF_ANGLE = 22,
	TEXTURE_SRC_CODE_WATER_COLOR = 23
} MaterialTextureSource;

