#include <stdint.h>

struct PrimitiveTemplate
{
	char mName[32];
	char mMaterialImpact[32];
	PrimType mType;
	int32_t mParentPrimIndex;
	FxRange mSpawnDelay;
	int64_t mSpawnCount;
	int64_t mLife;
	int64_t mSpawnRange;
	MediaHandles mMediaHandles;
	int64_t mImpactFxHandles;
	int64_t mDeathFxHandles;
	int64_t mEmitterFxHandles;
	int64_t mPlayFxHandles;
	int32_t mAttributeFlags;
	int32_t mSpawnFlags;
	int32_t mGroupFlags;
	int8_t mNonUniformScale;
	int8_t useLength;
	char pad0[2];
	char mMin[12];
	char mMax[12];
	int64_t mOrigin1X;
	int64_t mOrigin1Y;
	int64_t mOrigin1Z;
	int64_t mOrigin2X;
	int64_t mOrigin2Y;
	int64_t mOrigin2Z;
	int64_t mRadius;
	int64_t mHeight;
	int64_t mWindModifier;
	char mFxChannels[288];
	int64_t mRotation;
	int64_t mAngle1;
	int64_t mAngle2;
	int64_t mAngle3;
	int64_t mAngle1Delta;
	int64_t mAngle2Delta;
	int64_t mAngle3Delta;
	int64_t mGravity;
	int64_t mDensity;
	int64_t mVariance;
	int64_t mTexCoordS;
	int64_t mTexCoordT;
	int64_t mElasticity;
	StartFrameMode mSequenceStartFrameMode;
	int32_t mSequenceFixedFrameValue;
	PlayRateMode mSequencePlayRateMode;
	int32_t mSequenceFixedFpsValue;
	LoopMode mSequenceLoopMode;
	int32_t mSequenceLoopTimes;
	int32_t spawnFrustumCullRadius;
};

