#include <stdint.h>

typedef enum
{
	ANIM_ET_PAIN = 0,
	ANIM_ET_DEATH = 1,
	ANIM_ET_FIREWEAPON = 2,
	ANIM_ET_JUMP = 3,
	ANIM_ET_JUMPBK = 4,
	ANIM_ET_LAND = 5,
	ANIM_ET_DROPWEAPON = 6,
	ANIM_ET_RAISEWEAPON = 7,
	ANIM_ET_CLIMB_MOUNT = 8,
	ANIM_ET_CLIMB_DISMOUNT = 9,
	ANIM_ET_RELOAD = 10,
	ANIM_ET_CROUCH_TO_PRONE = 11,
	ANIM_ET_PRONE_TO_CROUCH = 12,
	ANIM_ET_STAND_TO_CROUCH = 13,
	ANIM_ET_CROUCH_TO_STAND = 14,
	ANIM_ET_STAND_TO_PRONE = 15,
	ANIM_ET_PRONE_TO_STAND = 16,
	ANIM_ET_MELEEATTACK = 17,
	ANIM_ET_SHELLSHOCK = 18,
	NUM_ANIM_EVENTTYPES = 19
} scriptAnimEventTypes_t;

