#include <stdint.h>

typedef enum
{
	SF_BAD = 0,
	SF_POLY = 1,
	SF_ENTITY = 2,
	SF_XMODEL_SKINNED = 3,
	SF_XMODEL_RIGID = 4,
	SF_STATICMODEL_CACHED = 5,
	SF_TRIANGLES = 6,
	SF_RAW_GEOMETRY = 7,
	SF_NUM_SURFACE_TYPES = 8,
	SF_MAX = 4294967295
} surfaceType_t;

