#include <stdint.h>

typedef enum
{
	UIMENU_NONE = 0,
	UIMENU_MAIN = 1,
	UIMENU_INGAME = 2,
	UIMENU_NEED_CD = 3,
	UIMENU_BAD_CD_KEY = 4,
	UIMENU_TEAM = 5,
	UIMENU_PREGAME = 6,
	UIMENU_POSTGAME = 7,
	UIMENU_WM_QUICKMESSAGE = 8,
	UIMENU_SCRIPT_POPUP = 9,
	UIMENU_SCRIPT_POPUP_NO_MOUSE = 10,
	UIMENU_PLAYER_PROFILE = 11
} uiMenuCommand_t;

