#include <stdint.h>

typedef enum
{
	WEAPOVERLAYRETICLE_NONE = 0,
	WEAPOVERLAYRETICLE_CROSSHAIR = 1,
	WEAPOVERLAYRETICLE_FG42 = 2,
	WEAPOVERLAYRETICLE_SPRINGFIELD = 3,
	WEAPOVERLAYRETICLE_BINOCULARS = 4,
	WEAPOVERLAYRETICLE_NUM = 5
} weapOverlayReticle_t;

