public: static int const std::_Locbase<int>::collate;
public: static int const std::_Locbase<int>::ctype;
public: static int const std::_Locbase<int>::monetary;
public: static int const std::_Locbase<int>::numeric;
public: static int const std::_Locbase<int>::time;
public: static int const std::_Locbase<int>::messages;
public: static int const std::_Locbase<int>::all;
public: static int const std::_Locbase<int>::none;
public: static unsigned int const std::ctype<char>::table_size;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::skipws;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::unitbuf;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::uppercase;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::showbase;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::showpoint;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::showpos;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::left;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::right;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::internal;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::dec;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::oct;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::hex;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::scientific;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::fixed;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::boolalpha;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::_Stdio;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::adjustfield;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::basefield;
public: static enum std::_Iosb<int>::_Fmtflags const std::_Iosb<int>::floatfield;
public: static enum std::_Iosb<int>::_Iostate const std::_Iosb<int>::goodbit;
public: static enum std::_Iosb<int>::_Iostate const std::_Iosb<int>::eofbit;
public: static enum std::_Iosb<int>::_Iostate const std::_Iosb<int>::failbit;
public: static enum std::_Iosb<int>::_Iostate const std::_Iosb<int>::badbit;
public: static enum std::_Iosb<int>::_Iostate const std::_Iosb<int>::_Hardfail;
public: static enum std::_Iosb<int>::_Openmode const std::_Iosb<int>::in;
public: static enum std::_Iosb<int>::_Openmode const std::_Iosb<int>::out;
public: static enum std::_Iosb<int>::_Openmode const std::_Iosb<int>::ate;
public: static enum std::_Iosb<int>::_Openmode const std::_Iosb<int>::app;
public: static enum std::_Iosb<int>::_Openmode const std::_Iosb<int>::trunc;
public: static enum std::_Iosb<int>::_Openmode const std::_Iosb<int>::_Nocreate;
public: static enum std::_Iosb<int>::_Openmode const std::_Iosb<int>::_Noreplace;
public: static enum std::_Iosb<int>::_Openmode const std::_Iosb<int>::binary;
public: static enum std::_Iosb<int>::_Seekdir const std::_Iosb<int>::beg;
public: static enum std::_Iosb<int>::_Seekdir const std::_Iosb<int>::cur;
public: static enum std::_Iosb<int>::_Seekdir const std::_Iosb<int>::end;
